### PR TITLE
Combined changes of other PRs

### PR DESCRIPTION
**Pull request by martinbutt**
Release v1.0.0 makes breaking changes to the config from the last stable version v0.0.40, so has a major version bump.

It incorporates all changes from https://github.com/openmiko/openmiko/releases/tag/v0.0.41-alpha.2 as well as the following:

# New Features
* Added Modules - allowing easy add-ons of bundled changes without recompiling the main Openmiko source. #82 
* Added config generators for initial set up. #89
* Added option to disable logging, as it seems likely that this is causing file-system corruption.

# Bug Fixes
* Cleaned up nightmode code and removed need for API to be enabled for nightmode to work. #85
* Added `fsck` to run at start up. #81 - Note requires an appropriate `fsck` module to be installed, e.g. [vfat](https://github.com/martinbutt/openmiko-module-fsck-vfat), [exfat](https://github.com/martinbutt/openmiko-module-fsck-exfat) or [ext](https://github.com/martinbutt/openmiko-module-fsck-ext).
* Added support for DOS-style line endings in `openmiko.conf`

# Documentation
* Improved developer documentation. #80

### CODE REVIEW

**Comment by jricks92** [comment]
@martinbutt What are the breaking changes with this? I looked through the code and I don't necessarily see anything that would break for someone if they upgrade from the current 0.0.41-alpha2. If there's no breaking changes I think we can merge this to master.

**Comment by martinbutt** [comment]
@jricks92 no breaking changes from `0.0.41-alpha2`, but as `0.0.41-alpha2` has breaking changes from `0.0.40`, I think it makes sense to start bumping the major version number.

**Comment by jricks92** [comment]
Ah totally make sense. I'll go ahead and merge to master then.

**Comment by martinbutt** [comment]
Great, thanks. If you want to create a release for it, then you can use the demo.bin here: https://github.com/martinbutt/openmiko/releases/tag/v1.0.0-alpha.3 (also note that these are typically named `openmiko_firmware.bin`, so should be renamed. That bin file was built with the updated ingenic_videocap submodule from [this PR](https://github.com/openmiko/ingenic_videocap/pull/14).

**Pull request merged**
