### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by schneemaier**
- updated ingenic_t20_defconfig to use the local kernel source file instead of downloading it from guthub every time
- linux_minimal_defconfig to not build RTL8188EU driver

### CODE REVIEW

**Comment by tachang** [comment]
Cool! Happy new year. Will take a look at this :)

**Comment by schneemaier** [comment]
Thanks

**Comment by tachang** [comment]
So I have a feeling the CONFIG_RTL8188EU=m is needed. Testing without it causes the camera not to connect to wifi.

**Comment by schneemaier** [comment]
Interesting. How is not building it differs from deleting the modul after building it. 

I have to do some tests.

**Comment by schneemaier** [comment]
So it is interesting. I made a comparison and found that if teh UE is not built, then the whole networking part is missing.

image

I don't know how did it work for me when I tested it

**Pull request merged**
